#!/usr/bin/env tsx
/**
 * generate-ts-tokens.ts
 *
 * Emits src/generated/tokens.ts — a typed, tree-shakeable TS module built
 * from the Style Dictionary outputs:
 *
 *   - dist/json/tailwind-tokens.json  -> theme / named groups
 *   - dist/json/tokens.json           -> flat dot-path map
 *   - tokens/dark-theme.json          -> darkColors
 *
 * Generated TS (instead of runtime JSON imports) keeps component .d.ts files
 * self-contained when the package is published — no relative JSON specifiers
 * leak into published declarations.
 *
 * Run automatically as part of `npm run tokens:sync`.
 */
import fs from "node:fs";
import path from "node:path";

const THEME_FILE =
  process.env.TOKENS_TW_FILE ??
  path.resolve(import.meta.dirname, "..", "dist", "json", "tailwind-tokens.json");
const FLAT_FILE =
  process.env.TOKENS_FLAT_FILE ??
  path.resolve(import.meta.dirname, "..", "dist", "json", "tokens.json");
const DARK_FILE =
  process.env.TOKENS_DARK_FILE ??
  path.resolve(import.meta.dirname, "..", "tokens", "dark-theme.json");
const OUT_DIR = path.resolve(import.meta.dirname, "..", "src", "generated");
const OUT_FILE = path.join(OUT_DIR, "tokens.ts");

interface ThemeTokens {
  readonly colors: Record<string, unknown>;
  readonly spacing: Record<string, string>;
  readonly borderRadius: Record<string, unknown>;
  readonly borderWidth: Record<string, unknown>;
  readonly boxShadow: Record<string, string>;
  readonly fontFamily: Record<string, readonly string[]>;
  readonly fontSize: Record<string, unknown>;
}

const theme = JSON.parse(fs.readFileSync(THEME_FILE, "utf8")) as ThemeTokens;
const flat = JSON.parse(fs.readFileSync(FLAT_FILE, "utf8")) as Record<
  string,
  unknown
>;
const dark = fs.existsSync(DARK_FILE)
  ? (JSON.parse(fs.readFileSync(DARK_FILE, "utf8")) as Record<string, string>)
  : {};

const banner = `// AUTO-GENERATED by scripts/generate-ts-tokens.ts — do not edit.
// Sources: dist/json/*.json + tokens/dark-theme.json. Re-run \`npm run tokens:sync\`.
`;

const json = (value: unknown): string => JSON.stringify(value, null, 2);

const out = `${banner}
/** Tailwind-shaped theme object (all values are light-mode). */
export const theme = ${json(theme)} as const;

export type ThemeTokens = typeof theme;

/** Semantic colors — every value is a \`var(--color-…)\` reference that
 *  follows the active theme (\`[data-theme="dark"]\`). */
export const colors = theme.colors;
export const spacing = theme.spacing;
export const borderRadius = theme.borderRadius;
export const borderWidth = theme.borderWidth;
export const boxShadow = theme.boxShadow;
export const fontFamily = theme.fontFamily;
export const fontSize = theme.fontSize;

/** Flat map of every token: \`"<dot.path>": <light value>\`.
 *  Composite entries (typography/shadow) hold structured values. */
export const flat = ${json(flat)} as const;

export type FlatTokenName = keyof typeof flat;

/** Dark-mode hex values, keyed by the same dot paths as \`flat\`
 *  (colors only). The stylesheet applies these automatically under
 *  \`[data-theme="dark"]\`; use this map for canvas/SVG/chart code. */
export const darkColors = ${json(dark)} as const;

export type DarkColorName = keyof typeof darkColors;
`;

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(OUT_FILE, out);
console.log(`Wrote ${OUT_FILE}`);
